<?php

namespace app\models;

use Yii;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "git_source".
 *
 * @property int $id
 * @property string $name
 * @property string $baseUrl
 */
class GitSource extends \yii\db\ActiveRecord
{
    use SelectableTrait;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'git_source';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'baseUrl'], 'required'],
            [['name', 'baseUrl'], 'string', 'max' => 100],
            [['baseUrl'], 'url']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('git-source', 'ID'),
            'name' => Yii::t('git-source', 'Name'),
            'baseUrl' => Yii::t('git-source', 'Base Url'),
        ];
    }

    public function beforeSave($insert)
    {
        if( substr($this->baseUrl, -1) !== '/' )
        {
            $this->baseUrl .= '/';
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function all(){
        return ArrayHelper::map(GitSource::find()
        ->addOrderBy(['name'=>SORT_ASC])
        ->all(),'id','name');
    }


}
