<?php

namespace app\models;

use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * Class User
 * @package app\models
 *
 * @property string $token_key
 *
 * @property UserGitSourceToken[] $gitSourceTokens
 */
class User extends \jki\user\models\User
{
    public function rules()
    {
        return [
                [['token_key'], 'string']
            ] +
            parent::rules(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->token_key = \Yii::$app->security->generateRandomKey(16);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * @return ActiveQuery
     */
    public function getGitSourceTokens()
    {
        return $this->hasMany(
            UserGitSourceToken::class,
            ['user_id' => 'id']
        );
    }

    public static function all()
    {
        return ArrayHelper::map(User::find()->all(), 'id', 'username');
    }
}
